### ISSUE TITLE
Log in credentials required at each launch

### ISSUE THREAD

**Issue by alvilag** [flathub/com.tutanota.Tutanota#77]
Since today's update, every time I close the app when I launch it again it requires me to fill in the email address and password (even if I previously checked the "store password" box). There's a message below the log in button that states "The system keychain has been invalidated. Deleting stored credentials".

Tutanota v3.91.10 running on Debian 11 stable (flatpak backport 1.12.4-1~bpo11+1).

Thanks for your attention!

**Comment by charlag** [comment]
This is fixed with 3.91.10-1

**Comment by charlag** [comment]
Could you please run it with `flatpak run com.tutanota.Tutanota` and see if there's any output about dbus and/or keychain?

**Comment by alvilag** [comment]
Here is the output:

> alvise@xps9300-deb:~$ flatpak run com.tutanota.Tutanota
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/lib/tutanota/tutanota-desktop --type=zygote --enable-crashpad
the monkey has been patched
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
version:   3.91.10
Gtk-Message: 17:10:15.694: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:10:15.694: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
resolving key... tutanota-vault
config up to date
[45:0210/171015.739950:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x00008D62. Skipping multisample checks.
[45:0210/171015.740164:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[45:0210/171015.740289:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[45:0210/171015.740341:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[45:0210/171015.740369:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[45:0210/171015.740817:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[45:0210/171015.740889:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[45:0210/171015.740921:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[45:0210/171015.740965:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[45:0210/171015.742102:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[ApplicationWindow] startFile:  file:///app/lib/tutanota/resources/app.asar/index-desktop.html
[DownloadManager] getting dictionaries from: https://mail.tutanota.com/desktop//dictionaries/
default mailto handler: false
[DownloadManager] spellcheck-dictionary-initialized en-GB
key tutanota-vault not found, generating a new one
libGL error: MESA-LOADER: failed to retrieve device information
[79:0210/171015.808907:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x00008D62. Skipping multisample checks.
[79:0210/171015.809116:ERROR:angle_platform_impl.cc(44)] renderergl_utils.cpp:496 (GenerateTextureFormatCaps): glGetInternalformativ generated error 0x00000500 for format 0x0000906F. Skipping multisample checks.
[79:0210/171015.809230:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: OpenGL ES 2.0 is not supportable.
[79:0210/171015.809341:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: OpenGL ES 2.0 is not supportable.
[79:0210/171015.809369:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[79:0210/171015.809685:ERROR:angle_platform_impl.cc(44)] Display.cpp:894 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[79:0210/171015.809719:ERROR:gl_surface_egl.cc(782)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[79:0210/171015.809746:ERROR:gl_surface_egl.cc(1382)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[79:0210/171015.809768:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[79:0210/171015.810576:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[96:0210/171015.846974:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
sseInfo corrupted or not present, making sure pushEncSessionKeys and scheduled alarms are cleared
Resetting stored state
invalidating alarms for all windows
invalidating alarms for window 1
Webapp ready
no update info on disk, disabling updater.
desktop file exists, checking version...
resolving key... tutanota-credentials
scheduling to check sse in 1 seconds
scheduling to check sse in 1 seconds
key tutanota-credentials not found, generating a new one
scheduling to check sse in 10 seconds
sse info not available, skip reconnect

**Comment by charlag** [comment]
>key tutanota-vault not found, generating a new one

what do you use for keychain? gnome-keyring-daemon or something else? Doesn't seem like anything was stored...

**Comment by alvilag** [comment]
Yes I am on gnome

> alvise@xps9300-deb:~$ gnome-keyring-daemon -V
gnome-keyring-daemon: 3.36.0
testing: enabled

BTW, I just checked with another machine and I encountered the same issue (Linux Mint 20.03).

**Comment by charlag** [comment]
Can you check with seahorse if any key is actually stored?
It seems like an issue with keychain provider and/or libsecret

**Comment by alvilag** [comment]
![seahorse](https://user-images.githubusercontent.com/66083813/153563388-5cd2d718-2fb0-4aec-9b9d-83aa54ddf9c4.png)

**Comment by zara1193** [comment]
Having the same issue across my devices, for what it's worth.

**Comment by charlag** [comment]
There should be two keys in keychain

**Comment by alvilag** [comment]
Seahorse lists only one entry having "app_id: com.tutanota.Tutanota".

**Comment by charlag** [comment]
@alvilag I don't think it's saving anything to your keychain. Here are our permissions:

https://github.com/flathub/com.tutanota.Tutanota/blob/550f11a5681a23e72366cb94f8ab62490eb1ea65/com.tutanota.Tutanota.json#L11-L24

I have no clue why it would fail

**Comment by Xathros1** [comment]
> @alvilag I don't think it's saving anything to your keychain. Here are our permissions:
> 
> https://github.com/flathub/com.tutanota.Tutanota/blob/550f11a5681a23e72366cb94f8ab62490eb1ea65/com.tutanota.Tutanota.json#L11-L24
> 
> I have no clue why it would fail

I've checked the permissions and they are all set correctly.

Also, I'm pretty sure that Seahorse (gnome keyring) only saved one entry, I've checked in the past and there was always only one.

However, I was wondering if the entry itself is saved correctly... ?

![Bildschirmfoto von 2022-02-11 15-13-34](https://user-images.githubusercontent.com/72621668/153608471-12a2b92a-3f65-48ad-ae35-32b556e6c86c.png)

**Comment by charlag** [comment]
In the past there was only one entry, now it's two entries:

https://github.com/tutao/tutanota/blob/b36f223ea62950d4522caaf0998c662cdc3ab5f7/src/desktop/KeyStoreFacadeImpl.ts#L19-L31

It says password but it's actually a binary key so it's not printable

**Comment by Xathros1** [comment]
OK, then there is really one missing...

11. Feb. 2022, 18:07 von ***@***.***:

**Comment by AwesamLinux** [comment]
I'm having the same issue on Linux Mint 20.3 after doing a recent flatpak update. I have tried:
- Deleting the two tutanota entries in Seahorse and reinstalling the tutanota flatpak
- Done a flatpak repair

This is the output of when launching the tutanota flatpak application, and then logging in again:

> ~$ flatpak run com.tutanota.Tutanota
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/lib/tutanota/tutanota-desktop --type=zygote --enable-crashpad
the monkey has been patched
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
version:   3.91.10
Gtk-Message: 11:26:17.042: Failed to load module "xapp-gtk3-module"
resolving key... tutanota-vault
config up to date
[ApplicationWindow] startFile:  file:///app/lib/tutanota/resources/app.asar/index-desktop.html
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open amdgpu: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/amdgpu_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: amdgpu
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: radeonsi
[DownloadManager] getting dictionaries from: https://mail.tutanota.com/desktop//dictionaries/
default mailto handler: false
[DownloadManager] spellcheck-dictionary-initialized en-US
scheduling to check sse in 1 seconds
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[45:0212/112617.220729:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[120:0212/112617.269224:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[2:0212/112617.295951:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:0212/112617.316305:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Webapp ready
no update info on disk, disabling updater.
[2:0212/112617.415477:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
desktop file exists, checking version...
resolving key... tutanota-credentials
key tutanota-credentials not found, generating a new one
last missed notification check: { lastMissedNotificationCheckTime: 1644661499921 }
scheduling to check sse in 108 seconds
starting sse connection
lookup sse request
established SSE connection
received new timeout: heartbeatTimeout:240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
downloading missed notification
lookup
missed notification response 200
dl missed notification response closed
MissedNotification is empty
scheduling to check sse in 288 seconds
[2:0212/112721.499120:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
resolving key... tutanota-credentials
key tutanota-credentials not found, generating a new one
storing push identifier
sse heartbeat 240
scheduling to check sse in 288 seconds``

**Comment by polzon** [comment]
Same issue on Fedora Workstation 36, on Tutanota v3.93.6.

**Comment by charlag** [comment]
I use Fedora (w/ GNOME) myself and I don't have this issue. Which DE do you use?

**Comment by Zlopez** [comment]
This issue is still happening on Fedora 36 Kinoite (Fedora Silverblue with KDE).

**Comment by HarlemSquirrel** [comment]
I'm still having this issue with Pop!_os so it's not. KDE issue, it's a flatpak issue.

**Comment by charlydelta** [comment]
I have this issue on GNOME. Debian 11.

**Comment by BuggStream** [comment]
So what exactly is the issue here and what steps need to be taken to fix it? Is it just an issue with the flatpak release of tutanota or an actual flatpak implementation issue? Or is it still unclear where the problem lies? I'd very much like to have this fixed and if there's any help required, please let us know.

**Comment by charlag** [comment]
1. Try AppImage. If that works for you, stick with it
2. If it still doesn't work make sure you have secret service provider installed. It can be anything, from gnome-keyring-daemon to KeePassXC to some other implementation.

**Comment by Zlopez** [comment]
Would switching to GNOME runtime instead of freedesktop runtime solve this?

**Comment by charlag** [comment]
@Zlopez we would hardcode users into GNOME runtime then and I'm not sure it would even help, someone could try building it

**Comment by Zlopez** [comment]
Maybe asking freedesktop project, if they wouldn't add some keyring manager to their runtime would be a better solution. Hardcoding users isn't really nice way of solving this.

**Comment by Neyl-123** [comment]
Maybe the label of the secret entry is messed up somehow. For the device key you have
```
serviceName: "tutanota-vault",
accountName: "tuta"
```
and for the credentials key you have
```
serviceName: "tutanota-credentials",
accountName: "tutanota-credentials"
```
If you track the SetPassword down to the [keytar posix version](https://github.com/atom/node-keytar/blob/fcabcab4b0ea25fca36d0202b4fcafe60a5a8d9c/src/keytar_posix.cc#L23-L47) you see that it sets `service + "/" + account` as the label but its not shown when you look at the keys via seahorse.
You only have `app_id: com.tutanota.Tutanota` and if you save both keys without label then it would override the first key with the second since it can't differentiate between them.
On the next login it tries to read the keys but no entry has a matching label and thus `key tutanota-vault not found, generating a new one` and `key tutanota-credentials not found, generating a new one` is printed.

**Comment by charlag** [comment]
There are two different keys
![Screenshot from 2022-05-16 07-15-47](https://user-images.githubusercontent.com/3099142/168524185-b78b4b4f-4aca-4b10-b197-1e593bc2dfe9.png)

Here are the key specs
https://github.com/tutao/tutanota/blob/86e180b2c8ff1a54f77d96655ef96bcd812bc392/src/desktop/KeyStoreFacadeImpl.ts#L21-L33

We had the problem you experience before dbus socket could be found. Since we changed permission to expose more of file system we couldn't reproduce it anymore. 

It could be caused by the fact that we build outside of flatpak container at the moment and it's somehow getting bound at compile time.

**Comment by Jegah** [comment]
Hi, 
I have been facing the same problem (on Fedora 36 Workstation with Gnome). The Flatpak version just seems to not create the keys correctly (as with others in this thread it was just creating one, with no label).

A "working" solution I found (Your mileage may vary):  
Downloading the appimage from the Tutanota website and running it once to log in and correctly create the two necessary keys. You can check with an app like Seahorse if it worked (It should look similarly to the screenshot from @charlag from the previous post). Once this was done you can delete the appimage and launch the Flatpak and log in there. After that, the credential should be found even after restarting the computer.

I believe, like many others, that Flatpak is the future of Linux app distribution, so it would be nice if a actual solution was found. It used to work without jumping through so many hoops.

**Comment by charlag** [comment]
Any help with debugging this is very welcome. The code is exactly the same in both cases so it looks like some funny libsecret/dbus bug?

**Comment by BretG137** [comment]
> Hi, I have been facing the same problem (on Fedora 36 Workstation with Gnome). The Flatpak version just seems to not create the keys correctly (as with others in this thread it was just creating one, with no label).
> 
> A "working" solution I found (Your mileage may vary): Downloading the appimage from the Tutanota website and running it once to log in and correctly create the two necessary keys. You can check with an app like Seahorse if it worked (It should look similarly to the screenshot from @charlag from the previous post). Once this is done you can delete the appimage and launch the Flatpak and log in there. After that, the credential should be found even after restarting the computer.
> 
> I believe, like many others, that Flatpak is the future of Linux app distribution, so it would be nice if a actual solution was found. It used to work without jumping through so many hoops.

Thanks!  This worked for me on Fedora Rawhide.

**Comment by jpkhawam** [comment]
> Hi, I have been facing the same problem (on Fedora 36 Workstation with Gnome). The Flatpak version just seems to not create the keys correctly (as with others in this thread it was just creating one, with no label).
> 
> A "working" solution I found (Your mileage may vary): Downloading the appimage from the Tutanota website and running it once to log in and correctly create the two necessary keys. You can check with an app like Seahorse if it worked (It should look similarly to the screenshot from @charlag from the previous post). Once this is done you can delete the appimage and launch the Flatpak and log in there. After that, the credential should be found even after restarting the computer.
> 
> I believe, like many others, that Flatpak is the future of Linux app distribution, so it would be nice if a actual solution was found. It used to work without jumping through so many hoops.

this also worked for me, for anyone trying this, just log in one last time to the flatpak and it should work from there

**Comment by juhojama** [comment]
> Hi, I have been facing the same problem (on Fedora 36 Workstation with Gnome). The Flatpak version just seems to not create the keys correctly (as with others in this thread it was just creating one, with no label).
> 
> A "working" solution I found (Your mileage may vary): Downloading the appimage from the Tutanota website and running it once to log in and correctly create the two necessary keys. You can check with an app like Seahorse if it worked (It should look similarly to the screenshot from @charlag from the previous post). Once this is done you can delete the appimage and launch the Flatpak and log in there. After that, the credential should be found even after restarting the computer.
> 
> I believe, like many others, that Flatpak is the future of Linux app distribution, so it would be nice if a actual solution was found. It used to work without jumping through so many hoops.

This fixed the problem also on Fedora 35 Silverblue

**Comment by neurodiverseEsoteric** [comment]
> Hi, I have been facing the same problem (on Fedora 36 Workstation with Gnome). The Flatpak version just seems to not create the keys correctly (as with others in this thread it was just creating one, with no label).
> 
> A "working" solution I found (Your mileage may vary): Downloading the appimage from the Tutanota website and running it once to log in and correctly create the two necessary keys. You can check with an app like Seahorse if it worked (It should look similarly to the screenshot from @charlag from the previous post). Once this is done you can delete the appimage and launch the Flatpak and log in there. After that, the credential should be found even after restarting the computer.
> 
> I believe, like many others, that Flatpak is the future of Linux app distribution, so it would be nice if a actual solution was found. It used to work without jumping through so many hoops.

Do you mean launch Flatpak in the Tutanota appimage's (extracted) directory? Do I set it to home? Or do I copy the ./config/tutanota-desktop directory to where flatpak puts that directory?

**Comment by CalliopeHummingbird** [comment]
The problem with switching to the appimage version is that after a week it tries to update itself and fails, but only after deleting the current version, so it has to be download, the execution permissions set, a launcher configured, etc.

Can't win.

**Comment by J0hn-Lawrence** [comment]
> Hi, I have been facing the same problem (on Fedora 36 Workstation with Gnome). The Flatpak version just seems to not create the keys correctly (as with others in this thread it was just creating one, with no label).
> 
> A "working" solution I found (Your mileage may vary): Downloading the appimage from the Tutanota website and running it once to log in and correctly create the two necessary keys. You can check with an app like Seahorse if it worked (It should look similarly to the screenshot from @charlag from the previous post). Once this is done you can delete the appimage and launch the Flatpak and log in there. After that, the credential should be found even after restarting the computer.
> 
> I believe, like many others, that Flatpak is the future of Linux app distribution, so it would be nice if a actual solution was found. It used to work without jumping through so many hoops.

Thank you! This worked on Fedora 37 Workstation.

**Comment by SvetlinZarev** [comment]
I have the same issue with 
* com.tutanota.Tutanota 3.108.12 
* Flatpak 1.14.1
* Debian Sid (unstable)

**Comment by dadoomer** [comment]
I also have the issue. Have had it for a long time.

- com.tutanota.Tutanota 3.112.5
- Flatpak 1.12.7
- Pop!_OS 22.04 LTS

**Comment by RaptaG** [comment]
Happens on my end too, are there any updates on this?

**Comment by pm4rcin** [comment]
I use fedora sericea and had the same problem so I have uninstalled `gnome-keyring` and deleted the files in `.local/share`. I use keepassxc flatpak and created new keyring in it and logged in to tutanota. Then I've closed tuta and opened it again and it worked just fine. Probably `gnome-keyring` is buggy or smth. If you guys have some questions on how to configure it please ask and I will try to help you. :)

**Comment by boniek83** [comment]
Using KDE. Flatpak needs socket=system-bus permission, then credentials are remembered.

**Comment by bbhtt** [comment]
> Using KDE. Flatpak needs socket=system-bus permission, then credentials are remembered.

Allowing access to entire system-bus is essentially removing any sandboxing. It should never be used https://docs.flatpak.org/en/latest/sandbox-permissions.html#d-bus-access

It's also blocked on the linter https://github.com/flathub/flatpak-builder-lint/blob/2d4bdb9fc63a636959aae9846da5a690028bcfba/flatpak_builder_lint/checks/finish_args.py#L59 so such a change in the manifest can't be merged.

**Comment by charlag** [comment]
okay, perfect, great so we are choosing between broken libsecret and no sandboxing?

Please, I beg you, can someone tell me how to make libsecret work with sandboxing.

Currently it shows this error on startup:

`Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

We are just using keytar which is just using libsecret. What we see from our side is that we tell libsecret to save the password and then it just disappears into the void. Any ideas how to approach it?

**Comment by charlag** [comment]
Do we perhaps need build libsecret in a special way?

**Comment by boniek83** [comment]
> > Using KDE. Flatpak needs socket=system-bus permission, then credentials are remembered.
> 
> Allowing access to entire system-bus is essentially removing any sandboxing. It should never be used https://docs.flatpak.org/en/latest/sandbox-permissions.html#d-bus-access
> 
> It's also blocked on the linter https://github.com/flathub/flatpak-builder-lint/blob/2d4bdb9fc63a636959aae9846da5a690028bcfba/flatpak_builder_lint/checks/finish_args.py#L59 so such a change in the manifest can't be merged.
> 
> Please try to investigate the actual issue.

Sure, but untill they fix this properly people can use Flatseal to allow a little bit of sanity back in their lives ;)

**Comment by bbhtt** [comment]
> `Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

That's coming from chromium, it's fine, every other electron app in a flatpak has it too.

This sounds like some app bug to me. The only other thing I can think of is `--filesystem=xdg-run/keyring` for a few edge cases. Element and a bunch of other apps on Flathub use node-keytar too and they work fine.

It seems to be correctly saving the password for me in the keyring as observed via dbus/seahorse entry.

Fwiw, I just created a new account to test:

After first login I can neither delete credentials not relogin after closing. This error pop ups which sounds like it could be related:

```
Feedback v3.118.12 - Error - UNKNOWN - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.118.12
 Timestamp (UTC): Thu, 28 Sep 2023 09:54:34 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.118.12 Chrome/116.0.5845.190 Electron/26.2.2 Safari/537.36
Error
 Error message: invalid mac
Stacktrace:
Error: invalid mac
    at Kt (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:1:364626)
    at Object.aesDecrypt (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:2:204631)
    at Object.aes256DecryptKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:14:128080)
    at uT.decryptUsingKeychain (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:2:279767)
    at async ipc (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:2:287911)
```

On the terminal I see `key tutanota-vault not found, generating a new one`

**Comment by charlag** [comment]
It may be an app bug that only happens on Flatpak and only without dbus access.

Which of the 2 password did it save to the keyring? Because we store 2 different keys

https://github.com/tutao/tutanota/blob/6af9e8d02cba661cbb271c02c292a036a32624ad/src/desktop/KeyStoreFacadeImpl.ts#L21-L33

The mac error you see is mismatch of the keystore key (which was just generated because we could not retrieve the key) and the stored data. That's exactly what is causing this error in the sandbox.

**Comment by bbhtt** [comment]
> Which of the 2 password did it save to the keyring? Because we store 2 different k

How can I tell? The description field is empty 

![image](https://github.com/flathub/com.tutanota.Tutanota/assets/62639087/8a9f5c58-ae58-4890-b2ef-32b6b652fc6e)

![image](https://github.com/flathub/com.tutanota.Tutanota/assets/62639087/691af069-2d1c-4486-a63d-e74dc5f07139)

**Comment by charlag** [comment]
exactly. Where are all the details? Why does unsandboxed installation work and sandboxed one throws away account/service?

For comparison, this is how it should look like:
![Screenshot from 2023-09-28 13-31-48](https://github.com/flathub/com.tutanota.Tutanota/assets/3099142/1d1fda29-bd61-4d61-87cb-4407a3dd1d69)
![Screenshot from 2023-09-28 13-33-42](https://github.com/flathub/com.tutanota.Tutanota/assets/3099142/d0f608a8-4769-4f07-9e08-de5c2578d19c)
![Screenshot from 2023-09-28 13-33-48](https://github.com/flathub/com.tutanota.Tutanota/assets/3099142/fd904885-2f5b-49b3-8c43-8f976680b3eb)

**Comment by charlag** [comment]
I think I will try to copy whatever Element is doing and see if it does anything

**Comment by charlag** [comment]
Would be nice if `xdg-run/keyring` was documented somewhere

**Comment by bbhtt** [comment]
I have seen the description missing in other Electron apps too but not sure whose bug that is.

And socket=session-bus, system-bus does not change any of this behaviour regarding description field or missing keys (expectedly because keytar uses libsecret apis to store the password and org.freedesktop.secrets is the only interface libsecret uses). system-bus would do nothing here as everything runs in user session.

**Comment by charlag** [comment]
I just tried to install peppermint os and installed gnome-keyring manually there and, surprise, everything just worked? with currently released flatpak, that is.

I will try something more preconfigured, like Ubuntu or Fedora next

**Comment by charlag** [comment]
Ubuntu is doing something funny?
After running Tutanota flatpak you *can't even see the keychain* in Seahorse until you relogin.

**Comment by charlag** [comment]
I've tried doing exactly the same as Element but nothing changed whatsoever

**Comment by charlag** [comment]
I did some snooping on d-bus and it seems like it's not even trying to write anything to the secret storage.

**Comment by charlag** [comment]
might be a hint

> Previously, libsecret used the D-Bus interface always and stored secrets in the host keyring. In 0.20 a mechanism to store the secrets inside the sandbox has been introduced and it is enabled by default when the application is run inside flatpak, and thus (I suppose) is causing issues if the D-Bus and non-D-Bus APIs are mixed.

https://gitlab.gnome.org/GNOME/libsecret/-/issues/49#note_1307164

**Comment by charlag** [comment]
Success! I patched libsecret to remove their flatpak switch and it *finally* works.
https://github.com/tutao/libsecret/commit/3d18f7e928d6de69457ec3d18d5ca84923191957

I think there's a bug somewhere in the backend/secrets portal.

if anyone could try the build from here and confirm that it works?
https://github.com/flathub/com.tutanota.Tutanota/pull/136#issuecomment-1740474194

**Comment by charlag** [comment]
Could have been that 0.21.1 also just fixed it
